<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.2 setup script
 */

/* Servers configuration */
$i = 0;

/* Server: upupw [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'upupw';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['hide_db'] = 'information_schema';
$cfg['Servers'][$i]['AllowNoPassword'] = false;

/* End of servers configuration */

$cfg['blowfish_secret'] = 'c7215f8c7cf45dfa919159bf2260c4ee.7cf45dfa919159bf';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['MaxDbList'] = 6000;
$cfg['MaxTableList'] = 6000;
$cfg['VersionCheck'] = false;
$cfg['SendErrorReports'] = 'never';
$cfg['DefaultLang'] = 'zh_CN';
$cfg['ServerDefault'] = 1;
?>